#pragma

enum {
	ERROR_INIT_OPENGL = 0x01,
	ERROR_INIT_SDL,
	ERROR_INIT_WINDOW,
	ERROR_INIT_RENDERER,
	ERROR_INIT_GL_CONTEXT,
	ERROR_INIT_GL_FUNCTIONS,
	ERROR_INIT_GL_CLASS,

	// OpenGL module errors
	ERROR_NULL_DATA_BUFF,
	ERROR_BUFFER_NOT_FOUND,
};